export const DB_HOST_CONFIG_KEY = 'DB_HOST';
export const DB_NAME_CONFIG_KEY = 'DB_NAME';
export const DB_PASSWORD_CONFIG_KEY = 'DB_PASSWORD';
export const DB_SYNCHRONIZE_CONFIG_KEY = 'DB_SYNCHRONIZE';
export const DB_USERNAME_CONFIG_KEY = 'DB_USERNAME';
export const DB_TYPE = 'postgres';
export const BEARER = 'Bearer';
export const REQUEST_USER_KEY = 'user';
export const DEFAULT_TOKEN_EXPIRY_DURATION = '60s';
export const ACCESS_TOKEN_EXPIRY_DURATION_CONFIG_KEY =
  'ACCESS_TOKEN_EXPIRY_DURATION';
export const ACCESS_TOKEN_JWT_SECRET_CONFIG_KEY = 'ACCESS_TOKEN_JWT_SECRET';
export const REFRESH_TOKEN_EXPIRY_DURATION_CONFIG_KEY =
  'REFRESH_TOKEN_EXPIRY_DURATION';
export const REFRESH_TOKEN_EXPIRY_DURATION_VALUE_CONFIG_KEY =
  'REFRESH_TOKEN_EXPIRY_DURATION_VALUE';
export const REFRESH_TOKEN_JWT_SECRET_CONFIG_KEY = 'REFRESH_TOKEN_JWT_SECRET';
export const REFRESH_TOKEN_COOKIE_KEY = 'refresh';
export const JWT_CLAIM_USER_ID = 'sub';
